baseurl: /dante-visualised

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - '*.log'
  - README.md
  - bundle # any user-specific listing goes at the end

include: [_pages]

sass:
  sass_dir: _sass
  style: compressed

title: Dante Visualised
description: Visualising Dante's Divine Comedy

author_name: Ginestra Ferraro
github_username: ginestra
twitter_username: ginez_17

# google_analytics: 

jekyll-minifier: {exclude: humans.txt}
kramdown: {hard_wrap: true}
markdown: kramdown
plugins: [jekyll-minifier]
theme: minima

url: https://ginestra.github.io